const boardEl=document.getElementById('board'),statusEl=document.getElementById('status'),resetEl=document.getElementById('reset'),startEl=document.getElementById('start'),winPanel=document.getElementById('win-panel'),winTitle=document.getElementById('win-title'),winCopy=document.getElementById('win-copy');
const SIZE=3;let cells=[],state=[],active=false,gameOver=false,computerTimer=null,redirectTimer=null;
function makeBoard(){boardEl.innerHTML='';cells=[];state=Array(9).fill(0);for(let i=0;i<9;i++){const r=Math.floor(i/3),c=i%3,b=document.createElement('button');b.className='cell';b.type='button';b.dataset.row=r;b.dataset.col=c;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`Hex cell ${i+1}`);b.addEventListener('click',()=>playerMove(i));boardEl.appendChild(b);cells.push(b)}}
function neighbors(i){const r=Math.floor(i/3),c=i%3,out=[];for(const [dr,dc] of [[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0]]){const nr=r+dr,nc=c+dc;if(nr>=0&&nr<SIZE&&nc>=0&&nc<SIZE)out.push(nr*SIZE+nc)}return out}
function pathFor(player){const starts=[],seen=new Set(),parent=new Map();if(player===1){for(let r=0;r<SIZE;r++)if(state[r*SIZE]===1)starts.push(r*SIZE)}else{for(let c=0;c<SIZE;c++)if(state[c]===2)starts.push(c)}const target=player===1?i=>i%SIZE===SIZE-1:i=>Math.floor(i/SIZE)===SIZE-1;const queue=[...starts];starts.forEach(i=>seen.add(i));while(queue.length){const i=queue.shift();if(target(i)){const path=[];let cur=i;while(cur!==undefined){path.unshift(cur);cur=parent.get(cur)}return path}for(const n of neighbors(i)){if(state[n]===player&&!seen.has(n)){seen.add(n);parent.set(n,i);queue.push(n)}}}return null}
function finish(player,path){if(gameOver)return;gameOver=true;active=false;if(computerTimer){clearTimeout(computerTimer);computerTimer=null}cells.forEach(cell=>cell.disabled=true);path.forEach(i=>cells[i].classList.add('winning'));if(player===1){statusEl.textContent='You won';winTitle.textContent='You made it.';winCopy.textContent='Your blue path reached from left to right. You found a winning connection.';winPanel.classList.add('show');redirectTimer=setTimeout(()=>window.location.replace('home.html'),2200)}else{statusEl.textContent='I won';winTitle.textContent='The computer crossed.';winCopy.textContent='My yellow path reached from top to bottom. My moves are random — try again.';winPanel.classList.add('show')}}
function checkWinner(){const userPath=pathFor(1);if(userPath){finish(1,userPath);return 1}const computerPath=pathFor(2);if(computerPath){finish(2,computerPath);return 2}return 0}
function setCell(i,player){if(gameOver||state[i]!==0)return false;state[i]=player;cells[i].classList.add(player===1?'user':'computer','filled');cells[i].disabled=true;return true}
function playerMove(i){if(!active||gameOver||state[i]!==0)return;if(!setCell(i,1))return;if(checkWinner())return;active=false;statusEl.textContent='My move…';computerTimer=setTimeout(computerMove,350+Math.random()*450)}
function computerMove(){computerTimer=null;if(gameOver)return;const open=[];state.forEach((v,i)=>{if(v===0)open.push(i)});if(!open.length)return;const choice=open[Math.floor(Math.random()*open.length)];setCell(choice,2);if(checkWinner())return;active=true;statusEl.textContent='Your move'}
function reset(){if(computerTimer)clearTimeout(computerTimer);if(redirectTimer)clearTimeout(redirectTimer);computerTimer=redirectTimer=null;gameOver=false;active=false;winPanel.classList.remove('show');makeBoard();statusEl.textContent='Your move';setTimeout(()=>{if(!gameOver)active=true},120)}
startEl.addEventListener('click',()=>{document.querySelector('.game-wrap').scrollIntoView({behavior:'smooth',block:'center'});active=true});resetEl.addEventListener('click',reset);makeBoard();setTimeout(()=>active=true,120);