const boardEl=document.getElementById('board');const statusEl=document.getElementById('status');const resetEl=document.getElementById('reset');const startEl=document.getElementById('start');const winPanel=document.getElementById('win-panel');const winTitle=document.getElementById('win-title');const winCopy=document.getElementById('win-copy');const SIZE=3;let cells=[];let state=[];let active=false;let gameOver=false;let computerTimer=null;let redirectTimer=null;
function makeBoard(){boardEl.innerHTML='';cells=[];for(let i=0;i<SIZE*SIZE;i++){const b=document.createElement('button');b.className='cell';b.type='button';b.setAttribute('role','gridcell');b.setAttribute('aria-label',`Cell ${i+1}`);b.addEventListener('click',()=>playerMove(i));boardEl.appendChild(b);cells.push(b)}state=Array(SIZE*SIZE).fill(0)}
function neighbors(i){const r=Math.floor(i/SIZE),c=i%SIZE;const out=[];for(const [dr,dc] of [[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0]]){const nr=r+dr,nc=c+dc;if(nr>=0&&nr<SIZE&&nc>=0&&nc<SIZE)out.push(nr*SIZE+nc)}return out}
function pathFor(player){const starts=[];const seen=new Set();if(player===1){for(let r=0;r<SIZE;r++)if(state[r*SIZE]===player)starts.push(r*SIZE);const target=i=>i%SIZE===SIZE-1}else{for(let c=0;c<SIZE;c++)if(state[c]===player)starts.push(c);const target=i=>Math.floor(i/SIZE)===SIZE-1}const q=[...starts];starts.forEach(x=>seen.add(x));let parent=new Map();while(q.length){const i=q.shift();if(target(i)){const path=[];let cur=i;while(cur!==undefined){path.push(cur);cur=parent.get(cur)}return path.reverse()}for(const n of neighbors(i)){if(state[n]===player&&!seen.has(n)){seen.add(n);parent.set(n,i);q.push(n)}}}return null}
function finish(player,path){gameOver=true;active=false;path.forEach(i=>cells[i].classList.add('winning'));if(player===1){statusEl.textContent='You won';winTitle.textContent='You made it.';winCopy.textContent='A connected path from left to right. Hex has no draw state — every completed board has a winner.';winPanel.classList.add('show');redirectTimer=setTimeout(()=>{window.location.href='home.html'},1800)}else{statusEl.textContent='I won';winTitle.textContent='The computer crossed.';winCopy.textContent='My yellow path reached top to bottom. Try another board — the moves are random.';setTimeout(()=>winPanel.classList.add('show'),450)}}
function check(){const a=pathFor(1);if(a){finish(1,a);return true}const b=pathFor(2);if(b){finish(2,b);return true}return false}
function setCell(i,player){state[i]=player;cells[i].classList.add(player===1?'user':'computer','filled');cells[i].disabled=true}
function playerMove(i){if(!active||gameOver||state[i])return;setCell(i,1);if(check())return;statusEl.textContent='My move…';active=false;computerTimer=setTimeout(computerMove,320+Math.random()*420)}
function computerMove(){computerTimer=null;if(gameOver)return;const open=[];state.forEach((v,i)=>{if(!v)open.push(i)});if(!open.length)return;const choice=open[Math.floor(Math.random()*open.length)];setCell(choice,2);if(check())return;active=true;statusEl.textContent='Your move'}
function reset(){if(computerTimer)clearTimeout(computerTimer);if(redirectTimer)clearTimeout(redirectTimer);computerTimer=null;redirectTimer=null;winPanel.classList.remove('show');gameOver=false;active=false;makeBoard();statusEl.textContent='Your move';setTimeout(()=>{active=true},120)}
startEl.addEventListener('click',()=>{document.querySelector('.game-wrap').scrollIntoView({behavior:'smooth',block:'center'});if(!active&&!gameOver)active=true});resetEl.addEventListener('click',reset);makeBoard();setTimeout(()=>{active=true},180);